In [1]:
# import used packages
import numpy as np
import pickle # save and laod binary files (data, model)

#Set jupyter display in full screen
from IPython.core.display import display, HTML
display(HTML("<style>.container {width:100% !important:=;}</style>"))

In [2]:
#function to import and export data from cPickle format

def unpickle(file):
    with open(file, 'rb') as fo:
        dict = pickle.load(fo, encoding = 'bytes')
    return dict

def save_obj(obj, name):
    with open('export/' + name + '.pkl', 'wb') as f:
        pickle.dump(obj, f, pickle.HIGHEST_PROTOCOL)

# 1) Préparer les données

In [3]:
# Importer les données dans des array numpy (2 fichiers: features et labels). Utiliser les fonctions de pickle définies plus haut.
# Regarder les dimensions des données
featuresFile = 'C:/Users/thiba/Documents/MASTER DS/Data_Science/Sigma_features.pkl'
labelFile = 'C:/Users/thiba/Documents/MASTER DS/Data_Science/Sigma_labels.pkl'

In [4]:
unpickle(featuresFile)

array([[625.0, 1.0, 64, ..., 1, 0, 0.0],
       [625.0, 1.0, 64, ..., 1, 0, 0.0],
       [954.0, 1.0, 64, ..., 0, 1, 0.0],
       ...,
       [1406.0, 8.0, 2048, ..., 0, 1, 271.0],
       [1582.0, 11.0, 352, ..., 0, 1, 113.0],
       [1423.0, 8.0, 2048, ..., 0, 1, 188.0]], dtype=object)

In [5]:
unpickle(labelFile)

array([  37.94,   39.95,   39.95,   39.95,   41.95,   41.95,   41.95,
         44.95,   44.95,   49.96,   49.99,   51.95,   52.96,   56.95,
         58.96,   61.95,   69.95,   72.95,   76.95,   78.95,   78.95,
         83.95,   84.95,   89.95,   89.95,   92.95,   92.95,   92.95,
         94.96,   94.96,   96.95,   99.95,   99.95,  104.95,  109.95,
        109.96,  119.95,  129.95,  129.95,  134.95,  134.95,  138.95,
        139.96,  139.99,  143.95,  144.95,  144.95,  149.95,  149.95,
        154.96,  154.96,  158.95,  159.95,  159.95,  159.95,  159.95,
        159.95,  164.95,  168.95,  169.96,  169.96,  169.96,  169.96,
        174.95,  175.96,  179.95,  184.96,  184.96,  187.96,  189.95,
        189.95,  194.95,  199.96,  199.96,  199.96,  207.95,  212.95,
        214.96,  214.96,  216.95,  219.95,  219.95,  219.95,  224.95,
        229.96,  229.96,  234.95,  249.95,  259.96,  264.95,  269.95,
        274.96,  274.96,  274.96,  274.96,  279.95,  279.95,  289.96,
        299.95,  312

In [6]:
# Ajouter le biai dans les variables (features). Equivaut à rajouter une variable (une colonne).

In [7]:
features = unpickle(featuresFile)
label = unpickle(labelFile)

print(len(features));

238


In [8]:
biai=np.ones((len(features),1))
print(biai)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.

In [9]:
featbiai=np.hstack([features,biai])

print(featbiai)

[[625.0 1.0 64 ... 0 0.0 1.0]
 [625.0 1.0 64 ... 0 0.0 1.0]
 [954.0 1.0 64 ... 1 0.0 1.0]
 ...
 [1406.0 8.0 2048 ... 1 271.0 1.0]
 [1582.0 11.0 352 ... 1 113.0 1.0]
 [1423.0 8.0 2048 ... 1 188.0 1.0]]


# 2) Définir le modèle (régression linéaire)

In [10]:
# Créer le vecteur de paramètres aléatoires (attention aux dimensions). Pour tester, il faut donc l'initialiser aléatoirement.

In [11]:
theta=np.random.rand(1,len(featbiai[0])).T

print(theta)

[[0.44230013]
 [0.0104347 ]
 [0.28445732]
 [0.43474923]
 [0.28915728]
 [0.26251696]
 [0.65611167]
 [0.30830695]
 [0.09996987]
 [0.6465411 ]
 [0.86677247]
 [0.05322391]
 [0.7806749 ]
 [0.02891223]
 [0.12306205]
 [0.30813829]
 [0.3599244 ]
 [0.88555179]
 [0.72260035]
 [0.63224808]
 [0.98095113]
 [0.01709088]
 [0.40367877]
 [0.76182508]
 [0.71173426]
 [0.51254525]
 [0.07178533]
 [0.37055965]
 [0.98543641]
 [0.24039835]
 [0.45999881]
 [0.49386216]
 [0.49990357]]


In [12]:
# Définition du modèle (hypothèse) qui permet de combiner les variables et les paramètres. On doit utiliser une fonction python.

In [13]:
# Multiplication matricielle
def modele(a,b):
    # a la matrice ligne de parametres, theta
    # b la matrice de variables, x
    # ressort une matrice ligne
    return np.dot(a,b)
    

In [14]:
featbiai.shape

(238, 33)

In [15]:
print(modele(featbiai,theta))

[[645.984427047182]
 [617.9246661832511]
 [859.841584623744]
 [646.5428925683001]
 [859.603068891796]
 [2690.199304247945]
 [859.603068891796]
 [647.8976519332143]
 [647.4719559006181]
 [646.5533272640247]
 [859.6135035875207]
 [628.9926042182158]
 [860.2007223660922]
 [859.6135035875207]
 [647.9083370616363]
 [646.9033061164728]
 [895.8898119186736]
 [1205.5163616818181]
 [999.2042156195739]
 [1490.4097189003503]
 [1485.4164680060794]
 [1502.0609216409239]
 [1092.3558184683732]
 [1483.289343621254]
 [1489.8138227512093]
 [1489.8138227512093]
 [1489.8138227512093]
 [1525.3640219653819]
 [1495.0171532640536]
 [1489.8138227512093]
 [3807.2816130650735]
 [1710.0535200824092]
 [1524.848130654161]
 [1710.0535200824092]
 [1514.4243162921941]
 [1562.3761540611379]
 [3796.7157166537554]
 [1502.6865054206899]
 [1661.4862613119828]
 [1702.8897494208004]
 [1731.22860329189]
 [1713.7843013192398]
 [1704.2347126543468]
 [3969.729464835557]
 [1734.1587474074884]
 [1730.591706394885]
 [1707.187649132

# 3) Descente de gradient

In [16]:
#Fonction de coût. Utilisation d'un fonction Python

In [17]:
label=label.reshape(-1,1)

In [18]:
label.shape

(238, 1)

In [19]:
theta.shape

(33, 1)

In [20]:
def cout(a,b,c):
    # a matrice des échantillons
    # b matrice des parametres
    # c matrice des valeurs réelles
    m = len(featbiai[0])
    return ((np.sum(np.square(modele(a, b)-c)))/(2*m));

In [21]:
m_cout = cout(featbiai,theta, label)

In [22]:
print(m_cout)

30577291.850966323


In [26]:
# Dérivée de la fonction de cout == gradients.
# Attention aux dimensions lors de la somme.
# Poser le caltul matriciel sur papier pour être sûr.

In [37]:
def d_cout(a,b,c):
    # a matrice des échantillons x
    # b matrice des parametres theta
    # c matrice des valeurs réelles y
    return (((modele(a, b) - c) * a).sum(axis=0) / a.shape[0]).reshape(a.shape[1],1)
    

In [32]:
len(featbiai[0])

33

In [30]:
np.sum(np.dot(featbiai.T,(modele(featbiai,theta)-label)))

5806518773.277067

In [39]:
d_cout(featbiai, theta, label).shape

(33, 1)

In [ ]:
# gradient descent : mise à jour des paramètres. Il faudra définir un alpha. On utilisera une fonction qui prendra l'objet paramètres en arguments.

In [ ]:
# Fonction pour tester l'évolution de la fonction de cout : vrai = continuer la descente du gradient
# Si la fonction de coût a diminué de moins de epsilon % entre deux étapes : on arrête la descente de gradients
# epsilon << 1 à fixer

# 4) Combination du tout dans une boucle

In [ ]:
# Initialisation. Créer une fonction d'initialisation qui
# retourne les objets dont on aura besoin pour notre descente de gradients (paramètres)

In [ ]:
# On utilise une boucle while pour implémenter notre descente de gradient en utilisant toutes les fonctions
# (tous les blocs de code) que nous avons créé.
# Penser à ajouter un affichage de monitoring de la descente de gradient