In [1]:
# import used packages
import numpy as np
import pickle # save and laod binary files (data, model)

#Set jupyter display in full screen
from IPython.core.display import display, HTML
display(HTML("<style>.container {width:100% !important:=;}</style>"))

In [2]:
#function to import and export data from cPickle format

def unpickle(file):
    with open(file, 'rb') as fo:
        dict = pickle.load(fo, encoding = 'bytes')
    return dict

def save_obj(obj, name):
    with open('export/' + name + '.pkl', 'wb') as f:
        pickle.dump(obj, f, pickle.HIGHEST_PROTOCOL)

# 1) Préparer les données

In [3]:
# Importer les données dans des array numpy (2 fichiers: features et labels). Utiliser les fonctions de pickle définies plus haut.
# Regarder les dimensions des données
featuresFile = 'D:/Program Files (x86)/Anaconda/0_SIGMA_DATA/Sigma_features.pkl'
labelFile = 'D:/Program Files (x86)/Anaconda/0_SIGMA_DATA/Sigma_labels.pkl'

In [4]:
unpickle(featuresFile)

array([[625.0, 1.0, 64, ..., 1, 0, 0.0],
       [625.0, 1.0, 64, ..., 1, 0, 0.0],
       [954.0, 1.0, 64, ..., 0, 1, 0.0],
       ...,
       [1406.0, 8.0, 2048, ..., 0, 1, 271.0],
       [1582.0, 11.0, 352, ..., 0, 1, 113.0],
       [1423.0, 8.0, 2048, ..., 0, 1, 188.0]], dtype=object)

In [5]:
unpickle(labelFile)

array([  37.94,   39.95,   39.95,   39.95,   41.95,   41.95,   41.95,
         44.95,   44.95,   49.96,   49.99,   51.95,   52.96,   56.95,
         58.96,   61.95,   69.95,   72.95,   76.95,   78.95,   78.95,
         83.95,   84.95,   89.95,   89.95,   92.95,   92.95,   92.95,
         94.96,   94.96,   96.95,   99.95,   99.95,  104.95,  109.95,
        109.96,  119.95,  129.95,  129.95,  134.95,  134.95,  138.95,
        139.96,  139.99,  143.95,  144.95,  144.95,  149.95,  149.95,
        154.96,  154.96,  158.95,  159.95,  159.95,  159.95,  159.95,
        159.95,  164.95,  168.95,  169.96,  169.96,  169.96,  169.96,
        174.95,  175.96,  179.95,  184.96,  184.96,  187.96,  189.95,
        189.95,  194.95,  199.96,  199.96,  199.96,  207.95,  212.95,
        214.96,  214.96,  216.95,  219.95,  219.95,  219.95,  224.95,
        229.96,  229.96,  234.95,  249.95,  259.96,  264.95,  269.95,
        274.96,  274.96,  274.96,  274.96,  279.95,  279.95,  289.96,
        299.95,  312

In [6]:
# Ajouter le biai dans les variables (features). Equivaut à rajouter une variable (une colonne).

In [7]:
features = unpickle(featuresFile)
label = unpickle(labelFile)

len(label)==len(features);
len(features);

In [8]:
biai=np.ones((len(features),1))

print(biai)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.

In [9]:
featbiai=np.hstack([features,biai])

print(featbiai)

[[625.0 1.0 64 ... 0 0.0 1.0]
 [625.0 1.0 64 ... 0 0.0 1.0]
 [954.0 1.0 64 ... 1 0.0 1.0]
 ...
 [1406.0 8.0 2048 ... 1 271.0 1.0]
 [1582.0 11.0 352 ... 1 113.0 1.0]
 [1423.0 8.0 2048 ... 1 188.0 1.0]]


# 2) Définir le modèle (régression linéaire)

In [10]:
# Créer le vecteur de paramètres aléatoires (attention aux dimensions). Pour tester, il faut donc l'initialiser aléatoirement.

In [11]:
theta=np.random.random((len(featbiai[0]),1))
print(theta)

[[0.12750358]
 [0.27870137]
 [0.12618021]
 [0.18006744]
 [0.56531419]
 [0.36381136]
 [0.00998144]
 [0.55578715]
 [0.05316759]
 [0.26927289]
 [0.51120669]
 [0.63829203]
 [0.42614382]
 [0.96345363]
 [0.56019878]
 [0.22753903]
 [0.45091376]
 [0.89145867]
 [0.49797196]
 [0.13866409]
 [0.87787882]
 [0.39900933]
 [0.04801106]
 [0.52359141]
 [0.1903337 ]
 [0.49237891]
 [0.5031309 ]
 [0.44207863]
 [0.43240745]
 [0.46379134]
 [0.16852281]
 [0.75830283]
 [0.01253693]]


In [12]:
# Définition du modèle (hypothèse) qui permet de combiner les variables et les paramètres. On doit utiliser une fonction python.

In [13]:
def modele(a,b):
    return np.dot(a,b) # fusion de matrices

In [14]:
print(len(featbiai),len(featbiai[0]))

238 33


In [15]:
print(modele(featbiai,theta))

[[301.11667648467875]
 [289.3989115725526]
 [384.7559500513178]
 [301.07209602526365]
 [384.6821673842059]
 [1144.0904295661921]
 [384.6821673842059]
 [301.2206252975551]
 [301.7245901966348]
 [301.35079739805786]
 [384.9608687570002]
 [292.865202359145]
 [385.7738661568804]
 [384.9608687570002]
 [301.50601550329645]
 [301.4971581162027]
 [487.82305581718333]
 [481.48855340749077]
 [538.5804082881036]
 [929.925204640137]
 [867.2387662681639]
 [871.6904154728982]
 [568.6166466633002]
 [841.6589843424895]
 [851.6055228217931]
 [851.6055228217931]
 [851.6055228217931]
 [778.4498782490933]
 [853.046964016195]
 [851.6055228217931]
 [1735.7954794910913]
 [940.7979914909366]
 [790.4414187335143]
 [940.7979914909366]
 [775.0592568864604]
 [850.8100940897519]
 [1720.5772336853872]
 [834.1545140008315]
 [997.9366466461977]
 [975.5313144283755]
 [1079.732127151698]
 [978.3254171379348]
 [1108.587735728837]
 [1892.5446374726807]
 [969.0231449957407]
 [983.1705530469077]
 [961.0253929502588]
 [946.

In [33]:
theta.shape

(33, 1)

# 3) Descente de gradient

In [16]:
#Fonction de coût. Utilisation d'un fonction Python

In [17]:
def cout(a,b):
    #a  matrice des vecteurs de parametre theta 
    #b  matrice des vraies valeurs
    m = b.shape[0] # le nombre d'exemples dans l'echantillon
    return  (np.sum(np.square(a-(b.reshape(-1,1))))/(2*m))

In [18]:
m_cout = cout(modele(featbiai,theta),label)

In [19]:
print(m_cout)

1477487.2904302767


In [20]:
np.square(modele(featbiai,theta)-label)

array([[69261.96304552126, 68208.03290605286, 68208.03290605286, ...,
        606581.3458179212, 638150.6555250044, 638150.6555250044],
       [63231.58420925283, 62224.75948473118, 62224.75948473118, ...,
        624971.0234138218, 657009.2780726883, 657009.2780726883],
       [120281.30320999818, 118891.14319079189, 118891.14319079189, ...,
        483294.7670840509, 511516.8330629972, 511516.8330629972],
       ...,
       [9603689.894600138, 9591236.0267629, 9591236.0267629, ...,
        4231134.112968146, 4149214.4906690745, 4149214.4906690745],
       [18595110.078238364, 18577779.055116434, 18577779.055116434, ...,
        10694173.909440415, 10563701.114381783, 10563701.114381783],
       [9232496.476778632, 9220285.737467473, 9220285.737467473, ...,
        3985981.6680108057, 3906482.4446205865, 3906482.4446205865]],
      dtype=object)

In [21]:
(modele(featbiai,theta) - label.reshape((-1,1))).shape

(238, 1)

In [22]:
label.shape

(238,)

In [23]:
# Dérivée de la fonction de cout == gradients.
# Attention aux dimensions lors de la somme.
# Poser le caltul matriciel sur papier pour être sûr.

In [24]:
def d_cout(a,b,c):
    # a matrice des vecteurs de parametre theta, y^
    # b vecteur des valeurs à prédire, y
    # c matrice des variables, x
    m = c.shape[0]
    return ((1/m)*np.dot(c.T,(a-b.reshape((-1,1)))))

In [25]:
(label.reshape(-1,1).shape)

(238, 1)

In [26]:
print(d_cout(modele(featbiai,theta),label,featbiai))

[[2156279.748435438]
 [10376.084846713373]
 [524014.9794359599]
 [7975746.365252931]
 [3322369.5725202146]
 [1113.86805309613]
 [262376.6859310447]
 [22.81678779342137]
 [334.73308084054105]
 [333.30809366961284]
 [106.87372947215421]
 [373.87237333041895]
 [153.78519306092576]
 [3.466693886536725]
 [144.6648575281249]
 [376.9958135141178]
 [1096.524996067618]
 [327.5185283112842]
 [1146.0022812704522]
 [20.36407266957104]
 [7.78498887201788]
 [1445.3717480401465]
 [13.759913380061183]
 [2.0603534198810824]
 [830.599268365425]
 [7.0449411049658535]
 [3.3342403946606103]
 [524.2322174951587]
 [92.48987542158373]
 [15.22841253664695]
 [1458.2923970450886]
 [191845.6837862411]
 [1473.5208095817356]]


In [27]:
np.sum([modele(featbiai,theta)-featbiai])

13242462.382455228

In [28]:
# gradient descent : mise à jour des paramètres. Il faudra définir un alpha. On utilisera une fonction qui prendra l'objet paramètres en arguments.

In [29]:
# Fonction pour tester l'évolution de la fonction de cout : vrai = continuer la descente du gradient
# Si la fonction de coût a diminué de moins de epsilon % entre deux étapes : on arrête la descente de fradients
# epsilon << 1 à fixer

# 4) Combination du tout dans une boucle

In [30]:
# Initialisation. Créer une fonction d'initialisation qui
# retourne les objets dont on aura besoin pour notre descente de gradients (paramètres)

In [31]:
# On utilise une boucle while pour implémenter notre descente de gradient en utilisant toutes les fonctions
# (tous les blocs de code) que nous avons créé.
# Penser à ajouter un affichage de monitoring de la descente de gradient